name: Dart tests and analysis

on:
  push:
    branches:
      - main

  Dart tests and analysis:
    name: Dart tests and analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
      - uses: invertase/github-action-dart-analyzer@v1
        with:
          working-directory: ./
        with:
          sdk: stable
      - name: Run analysis
        run: dart analyze
      - name: Run tests
        run: dart run test
